// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/liangtengfei/beer-admin/internal/data/ent/schema"
	"github.com/liangtengfei/beer-admin/internal/data/ent/syspost"
	"github.com/liangtengfei/beer-admin/internal/data/ent/sysuser"
	"github.com/liangtengfei/beer-admin/internal/data/ent/sysuserpost"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	syspostMixin := schema.SysPost{}.Mixin()
	syspostMixinFields0 := syspostMixin[0].Fields()
	_ = syspostMixinFields0
	syspostMixinFields1 := syspostMixin[1].Fields()
	_ = syspostMixinFields1
	syspostFields := schema.SysPost{}.Fields()
	_ = syspostFields
	// syspostDescCreatedAt is the schema descriptor for created_at field.
	syspostDescCreatedAt := syspostMixinFields0[0].Descriptor()
	// syspost.DefaultCreatedAt holds the default value on creation for the created_at field.
	syspost.DefaultCreatedAt = syspostDescCreatedAt.Default.(func() time.Time)
	// syspostDescUpdatedAt is the schema descriptor for updated_at field.
	syspostDescUpdatedAt := syspostMixinFields0[1].Descriptor()
	// syspost.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	syspost.DefaultUpdatedAt = syspostDescUpdatedAt.Default.(func() time.Time)
	// syspost.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	syspost.UpdateDefaultUpdatedAt = syspostDescUpdatedAt.UpdateDefault.(func() time.Time)
	// syspostDescCreatedBy is the schema descriptor for created_by field.
	syspostDescCreatedBy := syspostMixinFields1[0].Descriptor()
	// syspost.DefaultCreatedBy holds the default value on creation for the created_by field.
	syspost.DefaultCreatedBy = syspostDescCreatedBy.Default.(string)
	// syspostDescUpdatedBy is the schema descriptor for updated_by field.
	syspostDescUpdatedBy := syspostMixinFields1[1].Descriptor()
	// syspost.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	syspost.DefaultUpdatedBy = syspostDescUpdatedBy.Default.(string)
	// syspostDescPostName is the schema descriptor for post_name field.
	syspostDescPostName := syspostFields[1].Descriptor()
	// syspost.PostNameValidator is a validator for the "post_name" field. It is called by the builders before save.
	syspost.PostNameValidator = func() func(string) error {
		validators := syspostDescPostName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(post_name string) error {
			for _, fn := range fns {
				if err := fn(post_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	sysuserMixin := schema.SysUser{}.Mixin()
	sysuserMixinFields0 := sysuserMixin[0].Fields()
	_ = sysuserMixinFields0
	sysuserMixinFields1 := sysuserMixin[1].Fields()
	_ = sysuserMixinFields1
	sysuserFields := schema.SysUser{}.Fields()
	_ = sysuserFields
	// sysuserDescCreatedAt is the schema descriptor for created_at field.
	sysuserDescCreatedAt := sysuserMixinFields0[0].Descriptor()
	// sysuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysuser.DefaultCreatedAt = sysuserDescCreatedAt.Default.(func() time.Time)
	// sysuserDescUpdatedAt is the schema descriptor for updated_at field.
	sysuserDescUpdatedAt := sysuserMixinFields0[1].Descriptor()
	// sysuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysuser.DefaultUpdatedAt = sysuserDescUpdatedAt.Default.(func() time.Time)
	// sysuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sysuser.UpdateDefaultUpdatedAt = sysuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sysuserDescCreatedBy is the schema descriptor for created_by field.
	sysuserDescCreatedBy := sysuserMixinFields1[0].Descriptor()
	// sysuser.DefaultCreatedBy holds the default value on creation for the created_by field.
	sysuser.DefaultCreatedBy = sysuserDescCreatedBy.Default.(string)
	// sysuserDescUpdatedBy is the schema descriptor for updated_by field.
	sysuserDescUpdatedBy := sysuserMixinFields1[1].Descriptor()
	// sysuser.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	sysuser.DefaultUpdatedBy = sysuserDescUpdatedBy.Default.(string)
	// sysuserDescDeptID is the schema descriptor for dept_id field.
	sysuserDescDeptID := sysuserFields[1].Descriptor()
	// sysuser.DefaultDeptID holds the default value on creation for the dept_id field.
	sysuser.DefaultDeptID = sysuserDescDeptID.Default.(uint64)
	// sysuserDescUserName is the schema descriptor for user_name field.
	sysuserDescUserName := sysuserFields[2].Descriptor()
	// sysuser.UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	sysuser.UserNameValidator = func() func(string) error {
		validators := sysuserDescUserName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(user_name string) error {
			for _, fn := range fns {
				if err := fn(user_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysuserDescRealName is the schema descriptor for real_name field.
	sysuserDescRealName := sysuserFields[3].Descriptor()
	// sysuser.RealNameValidator is a validator for the "real_name" field. It is called by the builders before save.
	sysuser.RealNameValidator = sysuserDescRealName.Validators[0].(func(string) error)
	// sysuserDescMobile is the schema descriptor for mobile field.
	sysuserDescMobile := sysuserFields[4].Descriptor()
	// sysuser.MobileValidator is a validator for the "mobile" field. It is called by the builders before save.
	sysuser.MobileValidator = sysuserDescMobile.Validators[0].(func(string) error)
	// sysuserDescPassword is the schema descriptor for password field.
	sysuserDescPassword := sysuserFields[9].Descriptor()
	// sysuser.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	sysuser.PasswordValidator = func() func(string) error {
		validators := sysuserDescPassword.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password string) error {
			for _, fn := range fns {
				if err := fn(password); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	sysuserpostFields := schema.SysUserPost{}.Fields()
	_ = sysuserpostFields
	// sysuserpostDescCreatedAt is the schema descriptor for created_at field.
	sysuserpostDescCreatedAt := sysuserpostFields[2].Descriptor()
	// sysuserpost.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysuserpost.DefaultCreatedAt = sysuserpostDescCreatedAt.Default.(time.Time)
}
