// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/liangtengfei/beer-admin/internal/data/ent/predicate"
	"github.com/liangtengfei/beer-admin/internal/data/ent/syspost"
	"github.com/liangtengfei/beer-admin/internal/data/ent/sysuser"
	"github.com/liangtengfei/beer-admin/internal/data/ent/sysuserpost"
)

// SysUserPostQuery is the builder for querying SysUserPost entities.
type SysUserPostQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.SysUserPost
	withUser   *SysUserQuery
	withPost   *SysPostQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SysUserPostQuery builder.
func (supq *SysUserPostQuery) Where(ps ...predicate.SysUserPost) *SysUserPostQuery {
	supq.predicates = append(supq.predicates, ps...)
	return supq
}

// Limit the number of records to be returned by this query.
func (supq *SysUserPostQuery) Limit(limit int) *SysUserPostQuery {
	supq.ctx.Limit = &limit
	return supq
}

// Offset to start from.
func (supq *SysUserPostQuery) Offset(offset int) *SysUserPostQuery {
	supq.ctx.Offset = &offset
	return supq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (supq *SysUserPostQuery) Unique(unique bool) *SysUserPostQuery {
	supq.ctx.Unique = &unique
	return supq
}

// Order specifies how the records should be ordered.
func (supq *SysUserPostQuery) Order(o ...OrderFunc) *SysUserPostQuery {
	supq.order = append(supq.order, o...)
	return supq
}

// QueryUser chains the current query on the "user" edge.
func (supq *SysUserPostQuery) QueryUser() *SysUserQuery {
	query := (&SysUserClient{config: supq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := supq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := supq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sysuserpost.Table, sysuserpost.UserColumn, selector),
			sqlgraph.To(sysuser.Table, sysuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sysuserpost.UserTable, sysuserpost.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(supq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPost chains the current query on the "post" edge.
func (supq *SysUserPostQuery) QueryPost() *SysPostQuery {
	query := (&SysPostClient{config: supq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := supq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := supq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sysuserpost.Table, sysuserpost.PostColumn, selector),
			sqlgraph.To(syspost.Table, syspost.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sysuserpost.PostTable, sysuserpost.PostColumn),
		)
		fromU = sqlgraph.SetNeighbors(supq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SysUserPost entity from the query.
// Returns a *NotFoundError when no SysUserPost was found.
func (supq *SysUserPostQuery) First(ctx context.Context) (*SysUserPost, error) {
	nodes, err := supq.Limit(1).All(setContextOp(ctx, supq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sysuserpost.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (supq *SysUserPostQuery) FirstX(ctx context.Context) *SysUserPost {
	node, err := supq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single SysUserPost entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SysUserPost entity is found.
// Returns a *NotFoundError when no SysUserPost entities are found.
func (supq *SysUserPostQuery) Only(ctx context.Context) (*SysUserPost, error) {
	nodes, err := supq.Limit(2).All(setContextOp(ctx, supq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sysuserpost.Label}
	default:
		return nil, &NotSingularError{sysuserpost.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (supq *SysUserPostQuery) OnlyX(ctx context.Context) *SysUserPost {
	node, err := supq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of SysUserPosts.
func (supq *SysUserPostQuery) All(ctx context.Context) ([]*SysUserPost, error) {
	ctx = setContextOp(ctx, supq.ctx, "All")
	if err := supq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SysUserPost, *SysUserPostQuery]()
	return withInterceptors[[]*SysUserPost](ctx, supq, qr, supq.inters)
}

// AllX is like All, but panics if an error occurs.
func (supq *SysUserPostQuery) AllX(ctx context.Context) []*SysUserPost {
	nodes, err := supq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (supq *SysUserPostQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, supq.ctx, "Count")
	if err := supq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, supq, querierCount[*SysUserPostQuery](), supq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (supq *SysUserPostQuery) CountX(ctx context.Context) int {
	count, err := supq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (supq *SysUserPostQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, supq.ctx, "Exist")
	switch _, err := supq.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (supq *SysUserPostQuery) ExistX(ctx context.Context) bool {
	exist, err := supq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SysUserPostQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (supq *SysUserPostQuery) Clone() *SysUserPostQuery {
	if supq == nil {
		return nil
	}
	return &SysUserPostQuery{
		config:     supq.config,
		ctx:        supq.ctx.Clone(),
		order:      append([]OrderFunc{}, supq.order...),
		inters:     append([]Interceptor{}, supq.inters...),
		predicates: append([]predicate.SysUserPost{}, supq.predicates...),
		withUser:   supq.withUser.Clone(),
		withPost:   supq.withPost.Clone(),
		// clone intermediate query.
		sql:  supq.sql.Clone(),
		path: supq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (supq *SysUserPostQuery) WithUser(opts ...func(*SysUserQuery)) *SysUserPostQuery {
	query := (&SysUserClient{config: supq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	supq.withUser = query
	return supq
}

// WithPost tells the query-builder to eager-load the nodes that are connected to
// the "post" edge. The optional arguments are used to configure the query builder of the edge.
func (supq *SysUserPostQuery) WithPost(opts ...func(*SysPostQuery)) *SysUserPostQuery {
	query := (&SysPostClient{config: supq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	supq.withPost = query
	return supq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SysUserID uint64 `json:"sys_user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SysUserPost.Query().
//		GroupBy(sysuserpost.FieldSysUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (supq *SysUserPostQuery) GroupBy(field string, fields ...string) *SysUserPostGroupBy {
	supq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SysUserPostGroupBy{build: supq}
	grbuild.flds = &supq.ctx.Fields
	grbuild.label = sysuserpost.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SysUserID uint64 `json:"sys_user_id,omitempty"`
//	}
//
//	client.SysUserPost.Query().
//		Select(sysuserpost.FieldSysUserID).
//		Scan(ctx, &v)
func (supq *SysUserPostQuery) Select(fields ...string) *SysUserPostSelect {
	supq.ctx.Fields = append(supq.ctx.Fields, fields...)
	sbuild := &SysUserPostSelect{SysUserPostQuery: supq}
	sbuild.label = sysuserpost.Label
	sbuild.flds, sbuild.scan = &supq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SysUserPostSelect configured with the given aggregations.
func (supq *SysUserPostQuery) Aggregate(fns ...AggregateFunc) *SysUserPostSelect {
	return supq.Select().Aggregate(fns...)
}

func (supq *SysUserPostQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range supq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, supq); err != nil {
				return err
			}
		}
	}
	for _, f := range supq.ctx.Fields {
		if !sysuserpost.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if supq.path != nil {
		prev, err := supq.path(ctx)
		if err != nil {
			return err
		}
		supq.sql = prev
	}
	return nil
}

func (supq *SysUserPostQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SysUserPost, error) {
	var (
		nodes       = []*SysUserPost{}
		_spec       = supq.querySpec()
		loadedTypes = [2]bool{
			supq.withUser != nil,
			supq.withPost != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SysUserPost).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SysUserPost{config: supq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, supq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := supq.withUser; query != nil {
		if err := supq.loadUser(ctx, query, nodes, nil,
			func(n *SysUserPost, e *SysUser) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := supq.withPost; query != nil {
		if err := supq.loadPost(ctx, query, nodes, nil,
			func(n *SysUserPost, e *SysPost) { n.Edges.Post = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (supq *SysUserPostQuery) loadUser(ctx context.Context, query *SysUserQuery, nodes []*SysUserPost, init func(*SysUserPost), assign func(*SysUserPost, *SysUser)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*SysUserPost)
	for i := range nodes {
		fk := nodes[i].SysUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sysuser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "sys_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (supq *SysUserPostQuery) loadPost(ctx context.Context, query *SysPostQuery, nodes []*SysUserPost, init func(*SysUserPost), assign func(*SysUserPost, *SysPost)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*SysUserPost)
	for i := range nodes {
		fk := nodes[i].SysPostID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(syspost.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "sys_post_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (supq *SysUserPostQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := supq.querySpec()
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, supq.driver, _spec)
}

func (supq *SysUserPostQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sysuserpost.Table, sysuserpost.Columns, nil)
	_spec.From = supq.sql
	if unique := supq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if supq.path != nil {
		_spec.Unique = true
	}
	if fields := supq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
	}
	if ps := supq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := supq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := supq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := supq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (supq *SysUserPostQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(supq.driver.Dialect())
	t1 := builder.Table(sysuserpost.Table)
	columns := supq.ctx.Fields
	if len(columns) == 0 {
		columns = sysuserpost.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if supq.sql != nil {
		selector = supq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if supq.ctx.Unique != nil && *supq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range supq.predicates {
		p(selector)
	}
	for _, p := range supq.order {
		p(selector)
	}
	if offset := supq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := supq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SysUserPostGroupBy is the group-by builder for SysUserPost entities.
type SysUserPostGroupBy struct {
	selector
	build *SysUserPostQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (supgb *SysUserPostGroupBy) Aggregate(fns ...AggregateFunc) *SysUserPostGroupBy {
	supgb.fns = append(supgb.fns, fns...)
	return supgb
}

// Scan applies the selector query and scans the result into the given value.
func (supgb *SysUserPostGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, supgb.build.ctx, "GroupBy")
	if err := supgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SysUserPostQuery, *SysUserPostGroupBy](ctx, supgb.build, supgb, supgb.build.inters, v)
}

func (supgb *SysUserPostGroupBy) sqlScan(ctx context.Context, root *SysUserPostQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(supgb.fns))
	for _, fn := range supgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*supgb.flds)+len(supgb.fns))
		for _, f := range *supgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*supgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := supgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SysUserPostSelect is the builder for selecting fields of SysUserPost entities.
type SysUserPostSelect struct {
	*SysUserPostQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sups *SysUserPostSelect) Aggregate(fns ...AggregateFunc) *SysUserPostSelect {
	sups.fns = append(sups.fns, fns...)
	return sups
}

// Scan applies the selector query and scans the result into the given value.
func (sups *SysUserPostSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sups.ctx, "Select")
	if err := sups.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SysUserPostQuery, *SysUserPostSelect](ctx, sups.SysUserPostQuery, sups, sups.inters, v)
}

func (sups *SysUserPostSelect) sqlScan(ctx context.Context, root *SysUserPostQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sups.fns))
	for _, fn := range sups.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sups.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sups.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
