// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SysPost is the predicate function for syspost builders.
type SysPost func(*sql.Selector)

// SysUser is the predicate function for sysuser builders.
type SysUser func(*sql.Selector)

// SysUserPost is the predicate function for sysuserpost builders.
type SysUserPost func(*sql.Selector)
