// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SysPostColumns holds the columns for the "sys_post" table.
	SysPostColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "系统岗位"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeString, Nullable: true, Comment: "创建人员", Default: ""},
		{Name: "updated_by", Type: field.TypeString, Nullable: true, Comment: "更新人员", Default: ""},
		{Name: "post_name", Type: field.TypeString, Size: 100, Comment: "岗位名称"},
		{Name: "status", Type: field.TypeEnum, Comment: "状态: 0=ON 1=OFF", Enums: []string{"0", "1"}, Default: "0"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
	}
	// SysPostTable holds the schema information for the "sys_post" table.
	SysPostTable = &schema.Table{
		Name:       "sys_post",
		Columns:    SysPostColumns,
		PrimaryKey: []*schema.Column{SysPostColumns[0]},
	}
	// SysUserColumns holds the columns for the "sys_user" table.
	SysUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "系统用户"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeString, Nullable: true, Comment: "创建人员", Default: ""},
		{Name: "updated_by", Type: field.TypeString, Nullable: true, Comment: "更新人员", Default: ""},
		{Name: "dept_id", Type: field.TypeUint64, Nullable: true, Comment: "部门编号", Default: 0},
		{Name: "user_name", Type: field.TypeString, Unique: true, Size: 100, Comment: "登陆用户名称"},
		{Name: "real_name", Type: field.TypeString, Comment: "真实姓名"},
		{Name: "mobile", Type: field.TypeString, Comment: "手机号码"},
		{Name: "email", Type: field.TypeString, Nullable: true, Comment: "邮箱地址"},
		{Name: "avatar", Type: field.TypeString, Nullable: true, Comment: "头像地址"},
		{Name: "sex", Type: field.TypeEnum, Comment: "性别:male男性，female女性", Enums: []string{"male", "female"}, Default: "male"},
		{Name: "status", Type: field.TypeEnum, Comment: "状态: 0=ON 1=OFF", Enums: []string{"0", "1"}, Default: "0"},
		{Name: "password", Type: field.TypeString, Size: 100, Comment: "登陆密码"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
	}
	// SysUserTable holds the schema information for the "sys_user" table.
	SysUserTable = &schema.Table{
		Name:       "sys_user",
		Columns:    SysUserColumns,
		PrimaryKey: []*schema.Column{SysUserColumns[0]},
	}
	// SysUserPostColumns holds the columns for the "sys_user_post" table.
	SysUserPostColumns = []*schema.Column{
		{Name: "created_at", Type: field.TypeTime},
		{Name: "sys_user_id", Type: field.TypeUint64, Comment: "用户标识"},
		{Name: "sys_post_id", Type: field.TypeUint64, Comment: "岗位标识"},
	}
	// SysUserPostTable holds the schema information for the "sys_user_post" table.
	SysUserPostTable = &schema.Table{
		Name:       "sys_user_post",
		Columns:    SysUserPostColumns,
		PrimaryKey: []*schema.Column{SysUserPostColumns[1], SysUserPostColumns[2]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_user_post_sys_user_user",
				Columns:    []*schema.Column{SysUserPostColumns[1]},
				RefColumns: []*schema.Column{SysUserColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sys_user_post_sys_post_post",
				Columns:    []*schema.Column{SysUserPostColumns[2]},
				RefColumns: []*schema.Column{SysPostColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SysPostTable,
		SysUserTable,
		SysUserPostTable,
	}
)

func init() {
	SysPostTable.Annotation = &entsql.Annotation{
		Table: "sys_post",
	}
	SysUserTable.Annotation = &entsql.Annotation{
		Table:   "sys_user",
		Options: "COMMENT = '系统用户表'",
	}
	SysUserPostTable.ForeignKeys[0].RefTable = SysUserTable
	SysUserPostTable.ForeignKeys[1].RefTable = SysPostTable
	SysUserPostTable.Annotation = &entsql.Annotation{
		Table: "sys_user_post",
	}
}
