// Code generated by ent, DO NOT EDIT.

package syspost

import (
	"fmt"
	"time"
)

const (
	// Label holds the string label denoting the syspost type in the database.
	Label = "sys_post"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldPostName holds the string denoting the post_name field in the database.
	FieldPostName = "post_name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// EdgePostsUser holds the string denoting the posts_user edge name in mutations.
	EdgePostsUser = "posts_user"
	// EdgeSysUserPost holds the string denoting the sys_user_post edge name in mutations.
	EdgeSysUserPost = "sys_user_post"
	// Table holds the table name of the syspost in the database.
	Table = "sys_post"
	// PostsUserTable is the table that holds the posts_user relation/edge. The primary key declared below.
	PostsUserTable = "sys_user_post"
	// PostsUserInverseTable is the table name for the SysUser entity.
	// It exists in this package in order to avoid circular dependency with the "sysuser" package.
	PostsUserInverseTable = "sys_user"
	// SysUserPostTable is the table that holds the sys_user_post relation/edge.
	SysUserPostTable = "sys_user_post"
	// SysUserPostInverseTable is the table name for the SysUserPost entity.
	// It exists in this package in order to avoid circular dependency with the "sysuserpost" package.
	SysUserPostInverseTable = "sys_user_post"
	// SysUserPostColumn is the table column denoting the sys_user_post relation/edge.
	SysUserPostColumn = "sys_post_id"
)

// Columns holds all SQL columns for syspost fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldPostName,
	FieldStatus,
	FieldRemark,
}

var (
	// PostsUserPrimaryKey and PostsUserColumn2 are the table columns denoting the
	// primary key for the posts_user relation (M2M).
	PostsUserPrimaryKey = []string{"sys_user_id", "sys_post_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultCreatedBy holds the default value on creation for the "created_by" field.
	DefaultCreatedBy string
	// DefaultUpdatedBy holds the default value on creation for the "updated_by" field.
	DefaultUpdatedBy string
	// PostNameValidator is a validator for the "post_name" field. It is called by the builders before save.
	PostNameValidator func(string) error
)

// Status defines the type for the "status" enum field.
type Status string

// Status0 is the default value of the Status enum.
const DefaultStatus = Status0

// Status values.
const (
	Status0 Status = "0"
	Status1 Status = "1"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case Status0, Status1:
		return nil
	default:
		return fmt.Errorf("syspost: invalid enum value for status field: %q", s)
	}
}
